CREATE SCHEMA IF NOT EXISTS `easyrbac` DEFAULT CHARACTER SET utf8mb4 
CREATE TABLE IF NOT EXISTS `easyrbac`.`user` (
  `Id` BIGINT(20) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Salt` VARCHAR(128) NOT NULL,
  `RealName` VARCHAR(45) NULL DEFAULT NULL,
  `Enable` BIT(1) NOT NULL DEFAULT b'1',
  `MobilePhone` VARCHAR(30) NULL DEFAULT NULL,
  `CreateTime` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4